baseURL = 'https://csklub-os-notes.netlify.app/'
languageCode = 'en-us'
title = 'CSKlub Operating System Notes'
theme = "ananke"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
